from .models import MinimapZone

ZONES = [
    # Order
    MinimapZone(name="Shop", team="ORDER", x=35, y=370),
    MinimapZone(name="Base", team="ORDER", x=80, y=315),
    MinimapZone(name="T2 Top", team="ORDER", x=50, y=220),
    MinimapZone(name="T1 Top", team="ORDER", x=45, y=125),
    MinimapZone(name="Gromp", team="ORDER", x=75, y=175),
    MinimapZone(name="Blue Buff", team="ORDER", x=115, y=190),
    MinimapZone(name="Wolves", team="ORDER", x=115, y=225),
    MinimapZone(name="T2 Mid", team="ORDER", x=145, y=260),
    MinimapZone(name="T1 Mid", team="ORDER", x=185, y=215),
    MinimapZone(name="Raptors", team="ORDER", x=195, y=255),
    MinimapZone(name="Red Buff", team="ORDER", x=210, y=285),
    MinimapZone(name="Krugs", team="ORDER", x=225, y=320),
    MinimapZone(name="T2 Bot", team="ORDER", x=190, y=355),
    MinimapZone(name="T1 Bot", team="ORDER", x=280, y=355),
    # River
    MinimapZone(name="River Top", team="NEUTRAL", x=100, y=110),
    MinimapZone(name="Baron", team="NEUTRAL", x=140, y=130),
    MinimapZone(name="River Mid Top", team="NEUTRAL", x=170, y=170),
    MinimapZone(name="River Mid Bot", team="NEUTRAL", x=230, y=230),
    MinimapZone(name="Drake", team="NEUTRAL", x=265, y=275),
    MinimapZone(name="River Bot", team="NEUTRAL", x=300, y=290),
    # Chaos
    MinimapZone(name="Shop", team="ORDER", x=370, y=35),
    MinimapZone(name="Base", team="CHAOS", x=315, y=80),
    MinimapZone(name="T2 Top", team="CHAOS", x=220, y=50),
    MinimapZone(name="T1 Top", team="CHAOS", x=125, y=45),
    MinimapZone(name="Krugs", team="CHAOS", x=180, y=82),
    MinimapZone(name="Red Buff", team="CHAOS", x=195, y=115),
    MinimapZone(name="Raptors", team="CHAOS", x=212, y=148),
    MinimapZone(name="T2 Mid", team="CHAOS", x=260, y=145),
    MinimapZone(name="T1 Mid", team="CHAOS", x=215, y=185),
    MinimapZone(name="Wolves", team="CHAOS", x=293, y=179),
    MinimapZone(name="Blue Buff", team="CHAOS", x=295, y=215),
    MinimapZone(name="Gromp", team="CHAOS", x=330, y=225),
    MinimapZone(name="T2 Bot", team="CHAOS", x=355, y=190),
    MinimapZone(name="T1 Bot", team="CHAOS", x=355, y=280),
]
